# network
name: bcnet
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric

info:
  Version: 2.1.0
  Size: 2 Orgs with 1 Peer
  Orderer: Raft
  Distribution: Multi Host
  StateDB: GoLevelDB

clients:
  Admin@org1.example.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: ../../fixtures/artifacts/crypto/peerOrganizations/org1.foresee.chain/users/Admin@org1.foresee.chain/msp/keystore/priv_sk
      clientSignedCert:
        path: ../../fixtures/artifacts/crypto/peerOrganizations/org1.foresee.chain/users/Admin@org1.foresee.chain/msp/signcerts/Admin@org1.foresee.chain-cert.pem
  Admin@org2.example.com:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/hfc-kvs/org2
        cryptoStore:
          path: /tmp/hfc-cvs/org2
      clientPrivateKey:
        path: ../../fixtures/artifacts/crypto/peerOrganizations/org2.foresee.chain/users/Admin@org2.foresee.chain/msp/keystore/priv_sk
      clientSignedCert:
        path: ../../fixtures/artifacts/crypto/peerOrganizations/org2.foresee.chain/users/Admin@org2.foresee.chain/msp/signcerts/Admin@org2.foresee.chain-cert.pem

channels:
  mychannel:
    configBinary: networks/fabric/config_raft/mychannel.tx
    created: true
    orderers:
      - orderer.foresee.chain
    peers:
      peer0.org1.foresee.chain:
        eventSource: true
      peer0.org2.foresee.chain:
        eventSource: true
    chaincodes:
      - id: landproperty
        version: v1
        language: golang
        endorsement-policy: { "identities": [{ "role": { "name": "member", "mspId": "Org1MSP" }},{ "role": { "name": "member", "mspId": "Org2MSP" }},{ "role": { "name": "admin", "mspId": "Org1MSP" }},{ "role": { "name": "admin", "mspId": "Org2MSP" }}],"policy": {"1-of": [{ "signed-by": 0}, { "signed-by": 1 }, { "signed-by": 2 }, { "signed-by": 3}]}}

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.foresee.chain
    certificateAuthorities:
      - ca.org1.foresee.chain
    adminPrivateKey:
      path: ../../fixtures/artifacts/crypto/peerOrganizations/org1.foresee.chain/users/Admin@org1.foresee.chain/msp/keystore/priv_sk
    signedCert:
      path: ../../fixtures/artifacts/crypto/peerOrganizations/org1.foresee.chain/users/Admin@org1.foresee.chain/msp/signcerts/Admin@org1.foresee.chain-cert.pem
  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.foresee.chain
    certificateAuthorities:
      - ca.org2.foresee.chain
    adminPrivateKey:
      path: ../../fixtures/artifacts/crypto/peerOrganizations/org2.foresee.chain/users/Admin@org2.foresee.chain/msp/keystore/priv_sk
    signedCert:
      path: ../../fixtures/artifacts/crypto/peerOrganizations/org2.foresee.chain/users/Admin@org2.foresee.chain/msp/signcerts/Admin@org2.foresee.chain-cert.pem

orderers:
  orderer.foresee.chain:
    url: grpcs://10.10.7.30:7050
    grpcOptions:
      ssl-target-name-override: orderer.foresee.chain
    tlsCACerts:
      path: ../../fixtures/artifacts/crypto/ordererOrganizations/foresee.chain/tlsca/tlsca.foresee.chain-cert.pem

peers:
  peer0.org1.foresee.chain:
    url: grpcs://10.10.7.30:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.foresee.chain
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: ../../fixtures/artifacts/crypto/peerOrganizations/org1.foresee.chain/tlsca/tlsca.org1.foresee.chain-cert.pem
  peer0.org2.foresee.chain:
    url: grpcs://10.10.7.33:9051
    grpcOptions:
      ssl-target-name-override: peer0.org2.foresee.chain
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: ../../fixtures/artifacts/crypto/peerOrganizations/org2.foresee.chain/tlsca/tlsca.org2.foresee.chain-cert.pem

certificateAuthorities:
  ca.org1.foresee.chain:
    url: https://10.10.7.32:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: ../../fixtures/artifacts/crypto/peerOrganizations/org1.foresee.chain/tlsca/tlsca.org1.foresee.chain-cert.pem
  ca.org2.foresee.chain:
    url: https://10.10.7.34:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: ../../fixtures/artifacts/crypto/peerOrganizations/org2.foresee.chain/tlsca/tlsca.org2.foresee.chain-cert.pem
